In [1]:
import torch
import numpy as np
from torch.autograd import Variable

In [2]:
# N, seq_length = 50000, 400
N, seq_length = 5, 4

In [3]:
X_num = torch.rand([N, 1, seq_length])
X_num

tensor([[[0.8570, 0.9569, 0.1505, 0.2188]],

        [[0.6174, 0.6137, 0.1890, 0.2436]],

        [[0.0664, 0.1445, 0.8277, 0.9541]],

        [[0.6199, 0.0647, 0.4318, 0.4296]],

        [[0.5215, 0.1565, 0.9277, 0.6832]]])

In [4]:
X_mask = torch.zeros([N, 1, seq_length])
X_mask

tensor([[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]])

In [5]:
X_mask[0, 0,2] = 1
X_mask

tensor([[[0., 0., 1., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]])

In [6]:
Y = torch.zeros([N, 1])
Y

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [7]:
for i in range(N):
    positions = np.random.choice(seq_length, size=2, replace=False)
    X_mask[i, 0, positions[0]] = 1
    X_mask[i, 0, positions[1]] = 1
    Y[i,0] = X_num[i, 0, positions[0]] + X_num[i, 0, positions[1]]

In [8]:
X_mask,Y

(tensor([[[1., 0., 1., 0.]],
 
         [[1., 1., 0., 0.]],
 
         [[0., 0., 1., 1.]],
 
         [[1., 0., 0., 1.]],
 
         [[1., 1., 0., 0.]]]),
 tensor([[1.0075],
         [1.2311],
         [1.7818],
         [1.0495],
         [0.6780]]))

In [10]:
X = torch.cat((X_num, X_mask), dim=1)
X,Y

(tensor([[[0.8570, 0.9569, 0.1505, 0.2188],
          [1.0000, 0.0000, 1.0000, 0.0000]],
 
         [[0.6174, 0.6137, 0.1890, 0.2436],
          [1.0000, 1.0000, 0.0000, 0.0000]],
 
         [[0.0664, 0.1445, 0.8277, 0.9541],
          [0.0000, 0.0000, 1.0000, 1.0000]],
 
         [[0.6199, 0.0647, 0.4318, 0.4296],
          [1.0000, 0.0000, 0.0000, 1.0000]],
 
         [[0.5215, 0.1565, 0.9277, 0.6832],
          [1.0000, 1.0000, 0.0000, 0.0000]]]),
 tensor([[1.0075],
         [1.2311],
         [1.7818],
         [1.0495],
         [0.6780]]))

In [1]:
add_test
TemporalConvNet(input_size, num_channels,                      kernel_size=kernel_size, dropout=dropout)
                 2        [30, 30, 30, 30, 30, 30, 30, 30]       7                         0.0
输入的x为[32, 2, 400]



char_cnn_test
TemporalConvNet(input_size, num_channels, kernel_size=kernel_size, dropout=dropout)
                   100     [450, 450, 100]      3                         0.1
输入的x为[32, 100, 400]


copymem_test
TemporalConvNet(input_size, num_channels,                      kernel_size=kernel_size, dropout=dropout)
                   1       [10, 10, 10, 10, 10, 10, 10, 10]        8                       0.0
输入的x为[32, 1, 1020]

IndentationError: unexpected indent (2366367712.py, line 3)