## 定义X,w,b,y_hat
X 表示数据集的特征矩阵

w 表示权重

b 表示偏置

y_hat 表示预测的y值

**目的是计算w对于损失函数loss的导数，这里的loss采用平方误差**

In [1]:
import torch

In [8]:
X = torch.tensor([[0.,1.], [2.,3.], [4.,5.]]).reshape(3, 2)
# w = torch.tensor([2, -3.4]).reshape(2, 1)
w = torch.tensor([0., 0.]).reshape(2, 1)
w.requires_grad_(True)
b = torch.tensor(4.2, requires_grad=True)
y_hat = torch.tensor([0., 1., 2.]).reshape(3, 1)

In [9]:
## 计算y值
y = torch.matmul(X, w) + b
y

tensor([[4.2000],
        [4.2000],
        [4.2000]], grad_fn=<AddBackward0>)

## 计算损失

In [10]:
loss = 0.5 * ((y_hat - y) ** 2)
print(loss)

tensor([[8.8200],
        [5.1200],
        [2.4200]], grad_fn=<MulBackward0>)


## 调用torch内置的backward函数，计算梯度

In [11]:
loss.sum().backward(retain_graph=True)
print(w.grad)

tensor([[15.2000],
        [24.8000]])


## 用手动计算的公式求得梯度，其中X@w的导数为X

In [12]:
loss_d = (y_hat - X@w - b) * X * (-1)
print(loss_d)
print(loss_d.sum(0, keepdim=True))

tensor([[ 0.0000,  4.2000],
        [ 6.4000,  9.6000],
        [ 8.8000, 11.0000]], grad_fn=<MulBackward0>)
tensor([[15.2000, 24.8000]], grad_fn=<SumBackward1>)


In [13]:
loss_d = (y_hat - b) * X * (-1)
print(loss_d.sum(0, keepdim=True))

tensor([[15.2000, 24.8000]], grad_fn=<SumBackward1>)


In [20]:
x = 5
y = 0.5 * ((x - 2) ** 2) + 2
y_d = x - 2
for i in range(100):
    x = x - 0.1 * (x-2)
    print(x)

4.7
4.43
4.186999999999999
3.9682999999999993
3.7714699999999994
3.5943229999999993
3.4348906999999995
3.2914016299999997
3.1622614669999995
3.0460353202999997
2.9414317882699996
2.847288609443
2.7625597484987
2.68630377364883
2.617673396283947
2.555906056655552
2.500315450989997
2.450283905890997
2.4052555153018975
2.364729963771708
2.328256967394537
2.2954312706550835
2.2658881435895752
2.239299329230618
2.215369396307556
2.1938324566768004
2.1744492110091205
2.1570042899082082
2.1413038609173873
2.1271734748256486
2.1144561273430837
2.1030105146087754
2.092709463147898
2.083438516833108
2.075094665149797
2.0675851986348173
2.0608266787713356
2.054744010894202
2.0492696098047816
2.0443426488243035
2.039908383941873
2.0359175455476857
2.032325790992917
2.0290932118936253
2.026183890704263
2.0235655016338367
2.021208951470453
2.0190880563234077
2.017179250691067
2.0154613256219602
2.013915193059764
2.0125236737537877
2.011271306378409
2.0101441757405683
2.0091297581665115
2.00821678234