In [1]:
import torch
from IPython import display
from d2l import torch as d2l
import numpy as np

## softmax回归从零开始实现

### 拿到数据  数据是一个迭代器

In [2]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

### 定义超参数

In [3]:
# 超参数
num_epochs = 10
lr = 0.1

### 初始化模型参数

In [4]:
# 初始化模型参数
num_inputs = 784
num_outputs = 10

W = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)

### 定义softmax函数

In [5]:
# softmax函数
def softmax(X_):
    x_exp = torch.exp(X_)
    x_row_sum = x_exp.sum(axis=1, keepdim=True)
    return x_exp / x_row_sum

In [6]:
X_ = torch.tensor([[1,2,3],[4,5,6]])
torch.exp(X_)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [7]:
t = softmax(X_)
t.sum(axis = 1)

tensor([1., 1.])

### 构建模型

In [8]:
def softmax_reg_model(X_):
    return softmax(torch.matmul(X_, W) + b)

### 定义损失函数

In [9]:
def cross_entropy(y_hat, y):
    return -torch.log(y_hat[range(len(y)), y])

In [10]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
cross_entropy(y_hat, y)
#y_hat.shape, y.shape

tensor([2.3026, 0.6931])

### 构建精度函数 用于评估模型

In [11]:
def accuracy(y_hat, y):
    y_hat_pred = torch.argmax(y_hat,axis=1)
    com = y_hat_pred == y
    return com.sum() / len(y)

In [12]:
accuracy(y_hat, y)

tensor(0.5000)

### 构建优化器 sgd

In [13]:
def sgd(W, b, lr, batch_size):
    with torch.no_grad():
        W -= lr * W.grad / batch_size
        b -= lr * b.grad / batch_size
        W.grad.zero_()
        b.grad.zero_()

### 开始训练

In [14]:
for epoch in range(num_epochs):
    for X_, y in train_iter:
        X_ = X_.reshape(len(X_), -1)
        #print(X_.shape)
        y_hat = softmax_reg_model(X_)
        #print(y_hat.shape)
        #print(y.shape)
        loss = cross_entropy(y_hat, y)
        loss.sum().backward()
        sgd(W, b, lr, len(X_))

### 使用测试集预测  评估模型

In [15]:
def prediction():
    for X, y in test_iter:
        X = X.reshape(len(X), -1)
        y_hat = softmax_reg_model(X)
        print(accuracy(y_hat, y))
        
prediction()

tensor(0.8594)
tensor(0.8398)
tensor(0.8125)
tensor(0.8203)
tensor(0.8359)
tensor(0.8672)
tensor(0.8828)
tensor(0.8398)
tensor(0.8594)
tensor(0.8125)
tensor(0.8203)
tensor(0.7891)
tensor(0.7930)
tensor(0.8203)
tensor(0.8203)
tensor(0.8203)
tensor(0.8281)
tensor(0.8633)
tensor(0.8086)
tensor(0.8008)
tensor(0.8359)
tensor(0.8086)
tensor(0.8164)
tensor(0.8438)
tensor(0.8359)
tensor(0.7969)
tensor(0.8359)
tensor(0.8398)
tensor(0.8438)
tensor(0.8438)
tensor(0.8281)
tensor(0.8047)
tensor(0.8398)
tensor(0.8438)
tensor(0.7852)
tensor(0.8359)
tensor(0.8359)
tensor(0.8047)
tensor(0.8633)
tensor(0.8125)


## softmax回归的简单实现

In [18]:
# 构建模型
net = torch.nn.Sequential(torch.nn.Flatten(), torch.nn.Linear(784,10))
#net = nn.Sequential(nn.Flatten(), nn.Linear(784, 10))

# 构建损失函数
loss_f = torch.nn.CrossEntropyLoss(reduction='mean')

# 定义优化器
updater = torch.optim.SGD(net.parameters(), lr=0.1)

# 开始训练
for epoch in range(num_epochs):
#for epoch in range(100):
    for X_, y in train_iter:
        y_hat = net(X_)
        loss = loss_f(y_hat, y)
        updater.zero_grad()
        loss.backward()
        updater.step()

# 预测
for X, y in test_iter:
    X = X.reshape(len(X), -1)
    y_hat = softmax(net(X))
    print(accuracy(y_hat, y))

tensor(0.8555)
tensor(0.8555)
tensor(0.8359)
tensor(0.8359)
tensor(0.8359)
tensor(0.8594)
tensor(0.8633)
tensor(0.8516)
tensor(0.8633)
tensor(0.8125)
tensor(0.8398)
tensor(0.7930)
tensor(0.8008)
tensor(0.8359)
tensor(0.8242)
tensor(0.8320)
tensor(0.8281)
tensor(0.8711)
tensor(0.8164)
tensor(0.7930)
tensor(0.8320)
tensor(0.8203)
tensor(0.8086)
tensor(0.8477)
tensor(0.8477)
tensor(0.7930)
tensor(0.8359)
tensor(0.8359)
tensor(0.8555)
tensor(0.8594)
tensor(0.8320)
tensor(0.8086)
tensor(0.8555)
tensor(0.8320)
tensor(0.7891)
tensor(0.8516)
tensor(0.8438)
tensor(0.8164)
tensor(0.8750)
tensor(0.8750)
