### 线性回归的简单实现，使用nn模块

In [63]:
# 构建模型
net = torch.nn.Sequential(torch.nn.Linear(2, 1))

# 手动初始化参数
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

# 构建损失函数
# loss_f = torch.nn.MSELoss()
loss_f = torch.nn.HuberLoss(reduction='mean')

# 构建优化器
trainer = torch.optim.SGD(net.parameters(), lr=0.03)


# 训练
for epoch in range(epochs):
    for X_, y_ in get_batch(num_sample, X, y, batch_size):
        loss = loss_f(net(X_), y_.reshape(10,1))
        trainer.zero_grad()
        loss.backward()
        trainer.step()
    with torch.no_grad():
        train_loss = loss_f(net(X), y.reshape(1000,1))
        print(f'epoch {epoch + 1}, loss {float(train_loss):f}')

epoch 1, loss 2.243604
epoch 2, loss 0.415986
epoch 3, loss 0.001391
epoch 4, loss 0.000055
epoch 5, loss 0.000052


In [67]:
la = [1,2,3]
la.insert(0,2)
la

[2, 1, 2, 3]

In [68]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])

In [73]:
y=np.array([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y[[0,1],[0]]

array([0.1, 0.3])

In [76]:
import numpy as np 
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
rows = np.array([0,0,3,3]) 
cols = np.array([0,2,0,2]) 
y = x[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[ 0  2  9 11]


In [109]:
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y])

y = torch.tensor([0, 2])
y_hat = torch.tensor([[-1., 0., 0.], [0., 0., 1.0]])
cross_entropy(y_hat, y)

tensor([nan, -0.])

In [84]:
def cross_entropy_loss(y_true, y_pred):
    # 将输入转换为NumPy数组
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    # 计算交叉熵损失
    loss = -np.sum(y_true * np.log(y_pred))
    return loss

In [88]:
y_true = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]  # 真实标签
y_pred = [[0.7, 0.2, 0.1], [0.3, 0.4, 0.3], [0.1, 0.1, 0.8]]  # 模型输出概率

total_loss = []
num_samples = len(y_true)

for i in range(num_samples):
    loss = cross_entropy_loss(y_true[i], y_pred[i])
    total_loss.append(loss)

print("平均交叉熵损失:", total_loss)

平均交叉熵损失: [0.35667494393873245, 0.916290731874155, 0.2231435513142097]


In [89]:
y = torch.tensor([0, 1, 2])
y_hat = torch.tensor([[0.7, 0.2, 0.1], [0.3, 0.4, 0.3], [0.1, 0.1, 0.8]])
cross_entropy(y_hat, y)

tensor([0.3567, 0.9163, 0.2231])

In [91]:
torch.log(torch.tensor(0.7))

tensor(-0.3567)

In [92]:
[0.0] * 2

[0.0, 0.0]

In [94]:
def add1(*args):
    data = [a + float(b) for a, b in zip(data, args)]

x = [0,1,2]
y = [2]

In [95]:
import sys
assert ('linux' in sys.platform), "该代码只能在 Linux 下执行"

AssertionError: 该代码只能在 Linux 下执行

In [107]:
np.exp(750)

C:\Users\Coyle\AppData\Local\Temp\ipykernel_3116\3798726120.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(750)


inf